### ISSUE TITLE
Why Theano ?

### ISSUE THREAD

**Issue by ghost** [qiuqiangkong/sampleRNN_acoustic_scene_generation#1]
Hello,
thanks for the upload, I'm working on a conditional sampleRNN using pytorch and this is going to help a lot.
Why theano though ? It's obsolete and no longer supported. Is it only because the original paper used theano ?

**Comment by qiuqiangkong** [comment]
Hi Vincent,

    Yes, when we did the work we are based on the original theano implementation.


Best wishes,


Qiuqiang

________________________________
