### ISSUE TITLE
Does it work with music ?

### ISSUE THREAD

**Issue by ghost** [qiuqiangkong/sampleRNN_acoustic_scene_generation#2]
Do you think this would work with conditioned music ?
If so, how would you go about it ?

**Comment by qiuqiangkong** [comment]
Hi, yes definitely it will work conditioned on music. If you are conditioned on note, please try local condition. You may find more related research on conditional WaveNet.


Best wishes,


Qiuqiang

________________________________

**Comment by ghost** [comment]
Thanks for the quick answer.
I have troubles running the file, can you tell me your version of cuda, cudnn, numpy and theano please ? It seems like my versions are too recent.

**Comment by qiuqiangkong** [comment]
Try theano 1.0.3? As long as the cuda version works with theano it should work. What error did you get?


Best wishes,


Qiuqiang

________________________________

**Comment by ghost** [comment]
I get this 
```
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

/home/vincent/.local/lib/python2.7/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than
``` 

and this at the end : 

`
RuntimeError: Could not load cudnn library. Check your cudnn installation. Maybe using the Theano flag dnn.base_path can help you. Current value "/usr"`

Not sure what to do with this, i'm a beginner

**Comment by qiuqiangkong** [comment]
Theano should use compatible CUDA and CUDNN.

Try using the dependencies the same as here?

  *   cuDNN 5105
  *   Python 2.7.12
  *   Numpy 1.11.1
  *   Theano 0.8.2 (0.9 for WaveNet re-implementation)


Best wishes,


Qiuqiang

________________________________

**Comment by ghost** [comment]
Well you say in your readme to use Theano 1.0 !

**Comment by qiuqiangkong** [comment]
Yes I did use theano 1.0.3 (If I remembered correctly). The theano=0.8 follows the original SampleRNN implementation in https://github.com/soroushmehr/sampleRNN_ICLR2017


Best wishes,


Qiuqiang

________________________________

**Comment by ghost** [comment]
So I've managed to make it run, using cuda 9.1 and cudnn 7005. thanks !
